spring.application.name=creatorstore

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api





# spring.application.name=creatorstore

# spring.datasource.url=jdbc:postgresql://localhost:5432/creatorStore
# spring.datasource.username=postgres
# spring.datasource.password=Gopika0987@

# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=create

# spring.jpa.show-sql=true

# server.servlet.context-path=/api